### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by soillydude** [LytexWZ/TikTok-Unbanner#1]
If I waited the 3 days and the password is supposedly changed, how do I know what the new password is??

**Comment by LytexWZ** [comment]
What option you used, (if it is number better) and what pc you using to run the tool (windows Mac Linux)

**Comment by soillydude** [comment]
I used option 03 and I'm using a Lenovo PC

**Comment by LytexWZ** [comment]
Option 3 does not change the password, it only accepts the ban appeal request for you to get unbanned

**Comment by soillydude** [comment]
Ok thx. What option should I use then, if you know??

**Comment by LytexWZ** [comment]
Well it depends of the actual state of the account, is it banned? Is it under review?

**Comment by soillydude** [comment]
It got banned permanently.

**Comment by LytexWZ** [comment]
Select 04 and follow instruction, password will be displayed at the end of the process

**Comment by j6469m8v8x-ux** [comment]
displayed by what? i’ve been waiting on their reinstatement appeal email since oct 12, my 04 process said it was successful but i don’t know if i should repeat it
